// Generated by CoffeeScript 1.10.0
(function() {
  var Koalas,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Koalas = (function() {
    function Koalas(name, callback) {
      this.send = bind(this.send, this);
      this.sell = bind(this.sell, this);
      this.name = name;
      callback;
    }

    Koalas.prototype.sell = function() {
      return alert("test " + this.name + " !!");
    };

    Koalas.prototype.send = function(data) {
      return socket.emit('trans_data', data);
    };

    return Koalas;

  })();

}).call(this);

//# sourceMappingURL=koalas.js.map
